// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyTime_.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Yugege {

  #region Messages
  public sealed class NowTime : pb::IMessage {
    private static readonly pb::MessageParser<NowTime> _parser = new pb::MessageParser<NowTime>(() => new NowTime());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NowTime> Parser { get { return _parser; } }

    /// <summary>Field number for the "tim" field.</summary>
    public const int TimFieldNumber = 1;
    private string tim_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Tim {
      get { return tim_; }
      set {
        tim_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Tim.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Tim);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Tim.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tim);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Tim = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
